### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np

m = np.arange(12).reshape((3,4))

print(m)
print('\n overall: ', m.mean())

print('\n Raw: ', [m[i,:].mean() for i in range(3)])

print('\n Columns: ', [m[:,i].mean() for i in range(4)])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 overall:  5.5

 Raw:  [1.5, 5.5, 9.5]

 Columns:  [4.0, 5.0, 6.0, 7.0]


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [5]:
import numpy as np

u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

print('np: ','\n' , np . outer(u,v))

a = np.array([i*j for i in u for j in v]) . reshape((4,4))

print('\n list: ','\n',a)
print('\n numpy: ','\n', u*v.reshape(-1,1))


np:  
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

 list:  
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

 numpy:  
 [[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [6]:
import numpy as np
import numpy.random as npr

M = npr.random((10,6))
print(M)
print("\n\n")
x = np.any(M<0.1, axis=1)
M[x,:] = 0
print(M)


[[0.30522847 0.55247375 0.08284311 0.03335856 0.91271192 0.5369678 ]
 [0.24094858 0.30632232 0.32980239 0.19262335 0.99018141 0.39231661]
 [0.84230668 0.94115373 0.37946309 0.18946756 0.03869491 0.64572094]
 [0.67237338 0.85240165 0.54731796 0.37962044 0.16190634 0.58465951]
 [0.9197195  0.72106947 0.54743644 0.82102047 0.43319224 0.6811814 ]
 [0.64480208 0.67804718 0.29956621 0.47163604 0.63103175 0.50389898]
 [0.88582687 0.57011448 0.83237702 0.53239873 0.50714832 0.8461899 ]
 [0.48601333 0.96086922 0.76687598 0.57979937 0.62719321 0.70511865]
 [0.9966966  0.50906046 0.26813562 0.58645031 0.06197696 0.52377345]
 [0.3715523  0.52123228 0.93058196 0.34573423 0.03382508 0.48291328]]



[[0.         0.         0.         0.         0.         0.        ]
 [0.24094858 0.30632232 0.32980239 0.19262335 0.99018141 0.39231661]
 [0.         0.         0.         0.         0.         0.        ]
 [0.67237338 0.85240165 0.54731796 0.37962044 0.16190634 0.58465951]
 [0.9197195  0.72106947 0.5474

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.