### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [1]:
import numpy as np

m = np.arange(12).reshape((3,4))

print(m)

for i in range(m.shape[0]):
    print("Mean Row ", i, " = ", np.mean(m[i,:]))
    
for i in range(m.shape[1]):
    print("Mean Column ", i, " = ", np.mean(m[:, i]))
    
print("Overall Mean = ", np.mean(m))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean Row  0  =  1.5
Mean Row  1  =  5.5
Mean Row  2  =  9.5
Mean Column  0  =  4.0
Mean Column  1  =  5.0
Mean Column  2  =  6.0
Mean Column  3  =  7.0
Overall Mean =  5.5


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [2]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

out = np.outer(u, v)

print(out, "\n")

out1 = np.zeros((len(u), len(v)), 'uint16')

for i in range(len(u)):
    for j in range(len(v)):
        out1[i,j] = u[i]*v[j]
        
print(out1, "\n")

u = np.transpose(np.tile(u, (4, 1)))
out2 = u*v
print(out2)




[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [3]:
rndM = np.random.random(size = (10,6))

print(rndM, "\n")

rndM[np.any(rndM < 0.1, 1)] = 0

print(rndM)

[[2.67420928e-01 6.37285733e-02 8.60593161e-01 3.55043505e-01
  3.40814516e-01 3.60581385e-01]
 [7.07773999e-02 5.55630826e-01 1.18601007e-01 8.35860791e-01
  1.22611843e-01 4.86431591e-01]
 [9.99048880e-01 8.51003698e-01 2.10592609e-01 6.64889806e-02
  1.59761709e-01 3.88974626e-01]
 [9.21413996e-03 8.52503082e-01 9.51806592e-01 8.02872758e-01
  4.51075380e-01 9.20276739e-01]
 [4.42056766e-01 6.05494258e-01 4.10549988e-01 6.50392626e-01
  7.93485067e-01 6.54841886e-01]
 [8.31263603e-01 9.50299041e-01 2.30144663e-01 4.24391095e-03
  2.36039644e-01 1.59927645e-01]
 [8.83892326e-01 9.93951071e-01 3.55404508e-01 3.27184393e-02
  7.38698379e-04 8.00209806e-01]
 [3.40516888e-01 2.90077735e-01 8.97902548e-01 9.60782257e-01
  1.23702917e-01 5.76281954e-01]
 [8.39499452e-01 8.94894728e-01 2.84586524e-01 3.22265011e-01
  1.32410485e-02 1.87990794e-01]
 [7.25178441e-01 6.42428835e-01 7.72285138e-01 4.62540369e-01
  7.76763781e-01 2.15999199e-01]] 

[[0.         0.         0.         0.         0

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

In [4]:
import matplotlib.pyplot as plt # everybody imports it that way

%matplotlib inline 
# tell jupyter to plot inline



from math import pi
arr = np.linspace(0, 2*pi, 100)
#print(arr)
arr1 = arr[0:len(arr):10]
#print(arr1)
arr2 = arr[len(arr)::-1]
#print(arr2)

arr_fileterd = []
for i in range(0, len(arr)):
    if (abs(np.cos(arr[i]) - np.sin(arr[i])) < 0.1): arr_fileterd.append(arr[i])
    
        
print(arr_fileterd)

ycos = np.cos(arr)
ysin = np.sin(arr)

plt.plot(arr, ycos);
plt.plot(arr, ysin);
for i in range(len(arr_fileterd)): plt.axvline(x=arr_fileterd[i])

[0.7615982190520711, 0.8250647373064104, 3.8714576135146945, 3.934924131769034]


5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [5]:
a = np.array(np.fromfunction(lambda i,j: (i+1)*(j+1), (10,10)),'int')

print(a)

a_1 = a.reshape(100)

b = a_1[9:99:9]

print(b)

mask = np.ones((10,10))
mask = np.tril(mask, 1)
mask = np.triu(mask, 1)

c = a*mask
c = [i for i in c.reshape(100) if (i!=0)]
print(c)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[10 18 24 28 30 30 28 24 18 10]
[2.0, 6.0, 12.0, 20.0, 30.0, 42.0, 56.0, 72.0, 90.0]


6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

In [6]:
positions = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

distances = np.transpose(np.array(np.tile(positions, (len(positions), 1))))

distances = abs(positions - distances)

k = 1.60934 #mile to km factor

distances = k*distances

distances = np.ceil(distances*10)/10 #limit to 1 decimal digit in order to improve visualization

print(distances)

[[   0.   318.7  487.7 1184.5 1401.8 1891.  2373.8 2484.9 3078.7 3939.7]
 [ 318.7    0.   169.   865.9 1083.1 1572.4 2055.2 2166.2 2760.1 3621.1]
 [ 487.7  169.     0.   696.9  914.2 1403.4 1886.2 1997.2 2591.1 3452.1]
 [1184.5  865.9  696.9    0.   217.3  706.6 1189.4 1300.4 1894.2 2755.2]
 [1401.8 1083.1  914.2  217.3    0.   489.3  972.1 1083.1 1677.  2538. ]
 [1891.  1572.4 1403.4  706.6  489.3    0.   482.9  593.9 1187.7 2048.7]
 [2373.8 2055.2 1886.2 1189.4  972.1  482.9    0.   111.1  704.9 1565.9]
 [2484.9 2166.2 1997.2 1300.4 1083.1  593.9  111.1    0.   593.9 1454.9]
 [3078.7 2760.1 2591.1 1894.2 1677.  1187.7  704.9  593.9    0.   861. ]
 [3939.7 3621.1 3452.1 2755.2 2538.  2048.7 1565.9 1454.9  861.     0. ]]


7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [7]:
N = 100


#this funciton scales with N as O(N^2)
def get_prime_numbers(n):
        
    mask = np.ones(n+1, 'bool')
    numbers = np.arange(0,n+1)
    
    for i in np.arange(2,int(n/2)):
        for j in np.arange(1,n+1):
            if(numbers[j]%i==0 and numbers[j]!= i): mask[j] = 0
    
    numbers = numbers[mask]
    return numbers

def sieve_of_Eratosthenes(n):
    mask = np.ones(n+1, 'bool')
    numbers = np.arange(0, n+1)

    for i in np.arange(2, int(n**(0.5))):
        mask[i*2::i] = 0    
    
    numbers = numbers[mask]
    return numbers

#%timeit get_prime_numbers(N)                #2.42ms
#%timeit get_prime_numbers(N*10)             #234ms
#%timeit get_prime_numbers(N*100)            #24.2s

#%timeit sieve_of_Eratosthenes(N)             #11.1μs
#%timeit sieve_of_Eratosthenes(N*10)          #30.8μs
#%timeit sieve_of_Eratosthenes(N*100)         #120μs

print(get_prime_numbers(N))
print(sieve_of_Eratosthenes(N))

[ 0  1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79
 83 89 97]
[ 0  1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79
 83 89 97]


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

In [8]:
import matplotlib.pyplot as plt # everybody imports it that way

%matplotlib inline 


many_walkers = np.random.randint(-1,1,[200,1000])
many_walkers[many_walkers==0] = 1

walked_distance = np.zeros((200,1000), 'int')


for i in range(1000):
    for j in range(200):
        walked_distance[j,i] = np.sum(many_walkers[0:j,i])


walked_distance = walked_distance*walked_distance

mean_walked_squared = walked_distance.mean(axis = 1)

mean_walked = mean_walked_squared**0.5


plt.plot(range(200), mean_walked);

#I would have expected to get an average walked distance near to zero, not an incresing one

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.

In [9]:
a = np.array(np.loadtxt("populations.txt", usecols=range(0,4)), 'int')


plt.plot(a[:,0], a[:,1]);
plt.plot(a[:,0], a[:,2]);
plt.plot(a[:,0], a[:,3]);

hare_mean = int(a[:,1].mean())
lynxes_mean = int(a[:,2].mean())
carrot_mean = int(a[:,3].mean())


types = ["Hare", "Lynxes", "Carrot"]

for function in ['mean','median','std']:
    for i in range(1,4):
        print (types[i-1], " ",function, " = ", int(getattr(np, function)(a[:,i])))

print("Correlation factor Hare-Lynxes = ", np.corrcoef(a[:,1], a[:,2])[1,0])
print("Correlation factor Hare-Carrot = ", np.corrcoef(a[:,1], a[:,3])[1,0])
print("Correlation factor Lynxes-Carrot = ", np.corrcoef(a[:,2], a[:,3])[1,0])

Hare   mean  =  34080
Lynxes   mean  =  20166
Carrot   mean  =  42400
Hare   median  =  25400
Lynxes   median  =  12300
Carrot   median  =  41800
Hare   std  =  20897
Lynxes   std  =  16254
Carrot   std  =  3322
Correlation factor Hare-Lynxes =  0.07189206073535573
Correlation factor Hare-Carrot =  -0.016603777709879402
Correlation factor Lynxes-Carrot =  -0.6805771698401617
