### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [22]:
#code ex1

import numpy as np

m = np.arange(12).reshape((3,4))
print(m, '\n')


#row
for i in range(0,3):
    row = m[i]
    print("The", i, "row is:", row)
    
print("\n")
    
#column
for i in range(0,4):
    colmn=m[:,i]
    print("The", i, "column is:", colmn)
    
print("\n")


#overall means 
print("The overall means is:", np.mean(m))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

The 0 row is: [0 1 2 3]
The 1 row is: [4 5 6 7]
The 2 row is: [ 8  9 10 11]


The 0 column is: [0 4 8]
The 1 column is: [1 5 9]
The 2 column is: [ 2  6 10]
The 3 column is: [ 3  7 11]


The overall means is: 5.5


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [55]:
#code ex2

u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

print(u)
print(v)

print("\n")

# Using the function outer in numpy
product = np.outer(u,v)
print("Using the function outer in numpy:")
print(product)

print("\n")


# Using a nested for loop or list comprehension CORRECT-------------

print("Using a nested for loop or list comprehension ")
for i in range(4):
    result = np.array([(u[i]*v[j]) for j in range(4)])
    print(result)
    
print("\n")


# Using numpy broadcasting operations -----------------------------------------
print("Using numpy broadcasting operations")

[1 3 5 7]
[2 4 6 8]


Using the function outer in numpy:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


Using a nested for loop or list comprehension 
[2 4 6 8]
[ 6 12 18 24]
[10 20 30 40]
[14 28 42 56]


Using numpy broadcasting operations


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [97]:
#code ex3

import numpy as np

a = np.random.rand(10,6)  #UNIFORM 

print(a)

for i in range(10):
    for j in range(6):
        if  a[i,j] < 0.1: 
            a[i] = 0 

print("\n")
print(a)

            
    

[[0.0994919  0.24972978 0.52958141 0.24813693 0.21201371 0.92631059]
 [0.81010749 0.63523605 0.67386281 0.4443289  0.50524863 0.7250354 ]
 [0.17120153 0.56947306 0.33061393 0.8130902  0.52337588 0.1303463 ]
 [0.67163274 0.6040267  0.96211793 0.17565712 0.80890538 0.90423932]
 [0.91701336 0.02539898 0.7156386  0.85815634 0.03717317 0.01761958]
 [0.38128118 0.09219906 0.38818177 0.38615968 0.09474022 0.40205221]
 [0.37258027 0.85163884 0.18476542 0.81137996 0.35324564 0.55743419]
 [0.17535054 0.26531609 0.95206421 0.88533321 0.86122889 0.78306716]
 [0.15637074 0.523298   0.04583674 0.17443403 0.72694733 0.92581603]
 [0.5742999  0.40421393 0.5574196  0.9667977  0.38518428 0.72628237]]


[[0.         0.         0.         0.         0.         0.        ]
 [0.81010749 0.63523605 0.67386281 0.4443289  0.50524863 0.7250354 ]
 [0.17120153 0.56947306 0.33061393 0.8130902  0.52337588 0.1303463 ]
 [0.67163274 0.6040267  0.96211793 0.17565712 0.80890538 0.90423932]
 [0.         0.         0.     

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

In [ ]:
#code ex4




5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [ ]:
#code ex5

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

In [ ]:
#code ex6

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [ ]:
#code ex7

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

In [ ]:
#code ex8

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.

In [ ]:
#code ex9