### Numpy basics

In [1]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
m = np.arange(12).reshape((3,4))

for i, row in enumerate(m):
    print(f'The {i}-th row is {row}\n its mean is {row.mean()}')
print()
for i, col in enumerate(m.transpose()):
    print(f'The {i}-th col is {col}\n its mean is {col.mean()}')

The 0-th row is [0 1 2 3]
 its mean is 1.5
The 1-th row is [4 5 6 7]
 its mean is 5.5
The 2-th row is [ 8  9 10 11]
 its mean is 9.5

The 0-th col is [0 4 8]
 its mean is 4.0
The 1-th col is [1 5 9]
 its mean is 5.0
The 2-th col is [ 2  6 10]
 its mean is 6.0
The 3-th col is [ 3  7 11]
 its mean is 7.0


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [3]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

print("Using numpy's outer product:")
op = np.outer(u,v)
print(f'{op}')
print()
print("Using a list comprehension:")
op = np.array([h*v for h in u])
print(op)
print()
print("Using broadcasting operations:")
op = u.reshape(4,1)*v
print(op)

Using numpy's outer product:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using a list comprehension:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using broadcasting operations:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [24]:
import numpy.random as npr
m = npr.random([10,6])
print(f'The original matrix is:\n{m}\n')
# we review if theres any lower than zero each row (axis 1)
g = np.any(m<0.1,axis = 1)
# Then overwrite any such term
m[g>0]=np.zeros(6)
print(f'Thus, the resulting matrix is:\n{m}')

The original matrix is:
[[0.59626374 0.08009005 0.20805041 0.54140602 0.59781238 0.18928308]
 [0.98701551 0.54583712 0.85631476 0.43439753 0.41287558 0.91157221]
 [0.4498572  0.02122025 0.33548137 0.09681099 0.59179775 0.9893089 ]
 [0.40497096 0.92298013 0.22357918 0.43360229 0.43910123 0.8542114 ]
 [0.17330044 0.01137346 0.64171513 0.78762711 0.19974458 0.17043746]
 [0.87954361 0.16868232 0.46100788 0.25106192 0.94283105 0.79835235]
 [0.87279229 0.69936849 0.36881573 0.46088476 0.84559595 0.43631845]
 [0.63207929 0.80379096 0.26799154 0.55025044 0.40532679 0.22789302]
 [0.04658527 0.06241408 0.98397035 0.14259132 0.22567528 0.55803205]
 [0.7992804  0.86516226 0.82969281 0.48574621 0.0721953  0.34082505]]

Thus, the resulting matrix is:
[[0.         0.         0.         0.         0.         0.        ]
 [0.98701551 0.54583712 0.85631476 0.43439753 0.41287558 0.91157221]
 [0.         0.         0.         0.         0.         0.        ]
 [0.40497096 0.92298013 0.22357918 0.43360229 

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.