1. Find the row, column and overall means for the following matrix:

In [5]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)
print("Dimension=", m.ndim)
print ("Shape of the array:", m.shape)
print ("Size of the first dimension (axis):", len(m))
print(m.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimension count= 2
shape of the array: (3, 4)
size of the first dimension (axis): 3
int32


2. Find the outer product of the following two vecotrs

    u = np.array([1,3,5,7])
    v = np.array([2,4,6,8])

    Do this in the following ways:

    Using the function outer in numpy
    Using a nested for loop or list comprehension
    Using numpy broadcasting operatoins



In [8]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
print(u)
print(v)

#a
u_v_outer=np.outer(u,v)
print("Outer:","\n",u_v_outer)

#b
l=np.zeros((4,4))
i=0
j=0
for i in range(len(u)):
     for j in range(len(v)):
         l[i,j]=u[i]*v[j]
print("Loop:" , "\n" ,l)

#c
u_v =u * v.reshape((4, 1))
print(u_v)

[1 3 5 7]
[2 4 6 8]
with outer function : 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
with loop: 
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
[[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


3. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

In [9]:
rand_r = np.random.random((10,6))
print("(10,6) matrix:" , "\n",rand_r)

rand_r[(rand_r < 0.1).any(axis=1), :] = 0
print("New matrix:" , "\n",rand_r)

(10,6) matrix: 
 [[0.48799925 0.29355476 0.39722047 0.88067531 0.64278104 0.54483547]
 [0.30497721 0.89449421 0.52497406 0.10159829 0.05577484 0.25327645]
 [0.53738149 0.07227272 0.05049351 0.2845375  0.10554233 0.75162674]
 [0.67040435 0.0269838  0.84280317 0.03049504 0.34337024 0.30932202]
 [0.25406054 0.87849662 0.61538861 0.7088767  0.75600994 0.33108713]
 [0.06377317 0.2630489  0.20027365 0.87287273 0.46524256 0.84920729]
 [0.34776037 0.64500661 0.4034553  0.11654924 0.94713473 0.02025636]
 [0.86088703 0.49407739 0.52245856 0.59083368 0.6347546  0.0168405 ]
 [0.95077337 0.00788231 0.00807572 0.59847243 0.89221109 0.64657306]
 [0.5724685  0.40185126 0.00250767 0.05051433 0.03903195 0.53945467]]
New matrix: 
 [[0.48799925 0.29355476 0.39722047 0.88067531 0.64278104 0.54483547]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [

4. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

    Extract every 10th element using slice notation
    Reverse the array using slice notation
    Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
    Make a plot showing the sin and cos functions and indicate where they are close



In [ ]:
from numpy import pi
import matplotlib.pyplot as plt

x=np.linspace(0,2*pi,100)
print("main matrix:","\n",x)

#a) Extract every 10th element using slice notation
ex_x=x[::10]
print("Every 10th element is extracted:", "\n", ex_x)

#b)Reverse the array using slice notation
re_x=x[::-1]
print("reverse matrix:","\n",re_x)
re_ex_x=ex_x[::-1]
print("reverse extracted matrix:","\n",re_ex_x)

#c)Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
x_x = np.abs(np.sin(x)-np.cos(x)) < 0.1
print("nex matrix:","\n",x[x_x])

#d)Make a plot showing the sin and cos functions and indicate where they are close
plt.scatter(x[x_x], np.sin(x[x_x]))
plt.plot(x, np.sin(x), x, np.cos(x));

5. Create a matrix that shows the 10 by 10 multiplication table.

    Find the trace of the matrix
    Extract the anto-diagonal (this should be array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10]))
    Extract the diagnoal offset by 1 upwards (this should be array([ 2,  6, 12, 20, 30, 42, 56, 72, 90]))



In [ ]:
x=np.arange(1, 11)
m=x[:, None] * x[None, :]
print("multiplication table:","\n",m)

#a)Find the trace of the matrix
t_x=m.trace()
print("trace of matrix:",t_x)

#b)Extract the anto-diagonal
a_d=np.flipud(m).diagonal()
print("anto diagonal:", a_d)

#c)Extract the diagnoal offset by 1 upwards
o=m.diagonal(offset=1)
print("extracted:",o)

6. Use broadcasting to create a grid of distances

    Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

    Construct a 2D grid of distances among each city along Route 66
    Convert that in km (those savages...)



In [ ]:
m=np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
print("miles array:",m)

d= np.abs(m-m[:, np.newaxis])
print("distance array:","\n",d)
d_km = d/1.6
print("distance array in km:","\n" ,d_km)

7. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).

    Constract a shape (100,) boolean array, the mask
    Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
    Apply the mask to obtain an array of ordered prime numbers
    Check the performances (timeit); how does it scale with N?
    Implement the optimization suggested in the sieve of Eratosthenes



In [ ]:
p = np.ones((100,), dtype=bool)
print(p)



8. Diffusion using random walk

   Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

    Take 1000 walkers and let them walk for 200 steps
    Use randint to create a 2D array of size walkers x steps with values -1 or 1
    Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
    Take the square of that 2D array (elementwise)
    Compute the mean of the squared distances at each step (i.e. the mean along the columns)
    Plot the average distances (sqrt(distance**2)) as a function of time (step)

   Did you get what you expected?


In [ ]:
from pylab import *
import matplotlib.pyplot as plt
# Take 1000 walkers and let them walk for 200 steps

walker=1000
step= 200
step_m=np.arange(200).reshape(1,200)
print(step_m)

# Use randint to create a 2D array of size walkers x steps with values -1 or 1
u = 2*randint(0,2,size=(walker,step))-1
print("10000 walkers walk 200 steps:","\n",u)
#Build the actual walking distances for each walker
distt=np.sum(u,axis=1).tolist() #sum of steps
b=np.array(distt)

shape=(1000,1)
dist=b.reshape(shape)
print("distance matrix:","\n", dist)
#Take the square of that 2D array
square_dist=np.square(dist)
print("square of distances matrix:","\n",square_dist)
#Compute the mean of the squared distances at each step
mean=square_dist.mean(axis=1)
print("mean of each step matrix:","\n",mean)
#Plot the average distances (sqrt(distance**2)) as a function of time (step)

average_dist=np.sqrt(square_dist)
print(average_dist)
# plt.plot(step_m,average_dist)

9. Analyze a data file

    Download the population of hares, lynxes and carrots at the beginning of the last century.

    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt

    Check the content by looking within the file
    Load the data (use an appropriate numpy method) into a 2D array
    Create arrays out of the columns, the arrays being (in order): year, hares, lynxes, carrots
    Plot the 3 populations over the years
    Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
    Which species has the highest population each year?


In [ ]:
import matplotlib.pyplot as plt

#Load the into a 2D array
filename = '/Users/Selen/Desktop/populations.txt' #please download the file and change the address.
data = np.loadtxt(filename)
print(data)

#Create arrays out of the columns
year=np.array(data[:,:1])
print("*year*:","\n",year)
hares=np.array(data[:,1:2])
print("*hares*:","\n",hares)
lynxes=np.array(data[:,2:3])
print("*lynxes*:","\n",lynxes)
carrots=np.array(data[:,3:4])
print("*carrots*:","\n",carrots)
