# OSEMN Exercises

In [20]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [33]:
list_new = []

file1 = open("simple_data.txt",mode = 'w')

for i in range(0,10):
    var = np.random.randn()
    list_new.append(var)
    print(var)
    
for var1 in list_new:
    file1.write(str(var1))
    file1.write("\n")

-0.2846854570873182
1.2905460657170784
1.1376458345396783
0.6927609169945785
-0.21354542344531813
0.9487415654876588
1.3201308435017036
0.4730603325393829
0.11757492720555102
-1.1677011529062051


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [36]:
file1 = open("data.txt", mode ='w')

m = np.random.rand(5,5)
print(m)

file1.write(str(m))

[[0.64789099 0.9758519  0.88959282 0.8994628  0.97249638]
 [0.33169728 0.26627905 0.6141398  0.3982025  0.89662461]
 [0.2401046  0.08902403 0.08583395 0.25955935 0.94643638]
 [0.80754038 0.83235285 0.44408889 0.03663018 0.03384626]
 [0.96319846 0.0984448  0.04664581 0.86757342 0.55504403]]


290

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [9]:
#import pandas as pd

file2 = open("data.txt", 'r')

while(1):
    ch = (file2.read(1))
    if not ch:
        break
    
    
#dataframe1 = pd.read_csv("data.txt") 
#dataframe1.to_csv('data.csv', index = None) 

#file_csv = open("data.csv",'w')

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [26]:
file1 = open("credit_card.dat",'r')
vec = file1.readline() 
print(vec)

num = 0
a = np.array([])
counter = 0

for i in vec:
    if(counter <= 6):
        a
        
    

SyntaxError: unexpected EOF while parsing (<ipython-input-26-812c60c6fdce>, line 10)

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.