# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
import numpy.random as npr

npr.seed(1473458)

n = npr.randn(1,100)
#print(n)

with open('simple_data.txt', 'w') as f:
    for item in n:
        f.write("%s\n" % item)


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [3]:

npr.seed(176)

n = npr.randn(5,5)
print(n)

with open('data.txt', 'w') as f:
    for item in n:
        f.write("%s\n" % item)

[[-1.1935242  -0.59204713  1.11498899 -0.64099218  1.69026197]
 [-1.38982916 -1.16299335 -0.5268758  -1.31220448 -0.99975563]
 [-0.95341953 -0.4819436  -0.81267818 -1.57392681  0.14498341]
 [-1.21450942  1.01162958 -0.51555204  0.0816738  -0.19212592]
 [ 0.08019961  0.30638117  1.76059895  0.86638016 -1.48605341]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [7]:
#conversion: comma separated

vec=[]

with open('data.txt','r') as f:
    with open('data.csv','w') as f2:
        for line in f:
            content=line.split()
            #print(content)
            for i in content:
                f2.write(i)
                f2.write(',')

['[-1.1935242', '-0.59204713', '1.11498899', '-0.64099218', '1.69026197]']
['[-1.38982916', '-1.16299335', '-0.5268758', '-1.31220448', '-0.99975563]']
['[-0.95341953', '-0.4819436', '-0.81267818', '-1.57392681', '0.14498341]']
['[-1.21450942', '1.01162958', '-0.51555204', '0.0816738', '-0.19212592]']
['[', '0.08019961', '0.30638117', '1.76059895', '0.86638016', '-1.48605341]']


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [70]:
import sys

with open ("credit_card.dat", "rb") as infile:
    lines = infile.readlines()
    count = 0
    for line in lines:
        for i in range(19):
            sys.stdout.write(chr(int(line[i*6:(i+1)*6],2)))
        print("") #nonostante l'errore la lettura è corretta

7648 5673 3775 2271
3257 8247 3354 2266
2722 0001 4011 6652
0661 3063 3742 3150
0432 1608 1462 4742
5827 2027 8785 7303
5774 8528 2087 1117
8140 1210 6352 2845
5764 1133 7301 7100
6456 1737 4126 6726
1228 8631 7382 0000
7051 0160 5374 3166
0618 3587 1630 6376
1545 5454 7444 5636
6735 3116 3202 6834
7287 5011 1547 8413
7033 2607 3328 4200
2568 5244 1874 5024
1684 2253 7570 7118
0672 2576 0575 6631
6332 8353 8787 1340
1813 3361 1175 4211
2477 6450 8840 2368
5512 3505 2563 1326
3083 7882 0621 0025
4521 5148 8045 0334
7563 3654 8713 5787
8324 2664 0476 5561
0565 2504 7168 3510
5107 5507 1767 0738
2462 1821 2448 1443
2788 0638 6861 6554
5851 5873 5474 0547
0670 1004 4013 2655
5874 5506 3048 0806
2805 5401 8462 1260
5083 8406 6310 1862
1076 1445 3013 2266
8440 4804 4844 5277
4758 6141 0686 1387
7586 0675 0315 2568
2544 1258 7432 5165
3474 5023 4434 5626
1410 0270 0434 5086
7315 4446 1104 4215
0224 7742 8300 0266
0170 2700 3145 0640
2006 2437 8054 1600
8142 4055 1776 0026
3026 7380 1241 1084


ValueError: invalid literal for int() with base 2: b''

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.