# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [43]:
list_new = []
file1 = open("simple_data.txt",mode = 'w')
for i in range(0,10):
    var = np.random.randn()
    list_new.append(var)
    print(var)
    
for var1 in list_new:
    file1.write(str(var1))
    file1.write("\n")

0.21728112022357768
-0.22414180998068825
0.3769694703180064
-0.9391850791910242
2.850466112355895
-0.9307279540746094
-2.1409629636475556
-1.0973495361901349
-0.2671894167244963
-0.8582187181139961


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [49]:
m = np.arange(25).reshape(5,5)
print(m)

file1 = open("data.txt", mode ='w')
for i in range(0,5):
    for j in range(0,5):
        file1.write(str(m[i][j]))
        file1.write("\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [ ]:
file2 = open("data.txt", 'r')
file_csv = open("data.csv",'w')

while():
    var = file2.readlines()
    print(var)

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.