# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
randomlist = np.random.random(10)

In [3]:
f = open("simple_data.txt", "w")
for i in randomlist:
    f.write(str(i)+"\n")
f.close()

In [4]:
!cat simple_data.txt
!rm simple_data.txt

0.9620181016623995
0.334060400243426
0.5543958533940389
0.5054500353515561
0.38752692197711625
0.5371218411003624
0.12843443205519922
0.534116258504121
0.8417126327150241
0.8070592523742098


In [5]:
np.savetxt("simple_data.txt",randomlist)

In [6]:
!cat simple_data.txt
!rm simple_data.txt

9.620181016623995385e-01
3.340604002434259812e-01
5.543958533940388511e-01
5.054500353515560818e-01
3.875269219771162454e-01
5.371218411003624293e-01
1.284344320551992213e-01
5.341162585041210331e-01
8.417126327150240561e-01
8.070592523742098345e-01


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [7]:
randommatrix = np.random.random((5,5))
np.savetxt("data.txt",randommatrix)

In [8]:
!cat data.txt

2.570575631657117111e-01 1.704359386732762216e-01 4.872460546043377860e-01 1.642744825306454715e-01 1.262795462836467930e-01
2.000697442389487435e-01 1.356027890527214952e-01 8.661056229159606046e-01 4.684568925570198328e-02 4.417287250535937293e-01
7.769105301691895393e-01 8.837053734014550521e-01 2.331323388410777575e-02 9.894974167498484796e-01 2.911701970030445841e-01
6.412398221040018775e-01 3.968289955368382582e-01 1.038757357295467809e-01 8.262664932454300004e-02 2.319836596882640656e-01
4.438607100673760408e-01 9.048524074072902268e-01 1.895503551792622199e-01 5.303563903430958959e-01 9.059601697028534240e-01


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [9]:
randommatrix = []

shape1 = 0
shape2 = 0
with open("data.txt", "r") as f:
    for line in f:
        shape1 += 1
        for data in line.split():
            if shape1 == 1:
                shape2 += 1
            randommatrix.append(float(data))

randommatrix = np.array(randommatrix)
randommatrix.resize((shape1,shape2))

print(randommatrix)

[[0.25705756 0.17043594 0.48724605 0.16427448 0.12627955]
 [0.20006974 0.13560279 0.86610562 0.04684569 0.44172873]
 [0.77691053 0.88370537 0.02331323 0.98949742 0.2911702 ]
 [0.64123982 0.396829   0.10387574 0.08262665 0.23198366]
 [0.44386071 0.90485241 0.18955036 0.53035639 0.90596017]]


In [10]:
randommatrix = np.loadtxt("data.txt")
print(randommatrix)

[[0.25705756 0.17043594 0.48724605 0.16427448 0.12627955]
 [0.20006974 0.13560279 0.86610562 0.04684569 0.44172873]
 [0.77691053 0.88370537 0.02331323 0.98949742 0.2911702 ]
 [0.64123982 0.396829   0.10387574 0.08262665 0.23198366]
 [0.44386071 0.90485241 0.18955036 0.53035639 0.90596017]]


In [11]:
f = open("data.csv", "w")

for i in randommatrix:
    n = 1
    for a in i:
        if n != i.shape[0]:
            f.write(str(a)+",")
        else:
            f.write(str(a))
        n += 1
            
    f.write("\n")
f.close()

In [12]:
!cat data.csv
!rm data.csv

0.2570575631657117,0.17043593867327622,0.4872460546043378,0.16427448253064547,0.1262795462836468
0.20006974423894874,0.1356027890527215,0.8661056229159606,0.04684568925570198,0.44172872505359373
0.7769105301691895,0.883705373401455,0.023313233884107776,0.9894974167498485,0.2911701970030446
0.6412398221040019,0.39682899553683826,0.10387573572954678,0.082626649324543,0.23198365968826407
0.44386071006737604,0.9048524074072902,0.18955035517926222,0.5303563903430959,0.9059601697028534


In [13]:
np.savetxt("data.csv", randommatrix, delimiter=",")

In [14]:
!cat data.csv
!rm data.csv
!rm data.txt

2.570575631657117111e-01,1.704359386732762216e-01,4.872460546043377860e-01,1.642744825306454715e-01,1.262795462836467930e-01
2.000697442389487435e-01,1.356027890527214952e-01,8.661056229159606046e-01,4.684568925570198328e-02,4.417287250535937293e-01
7.769105301691895393e-01,8.837053734014550521e-01,2.331323388410777575e-02,9.894974167498484796e-01,2.911701970030445841e-01
6.412398221040018775e-01,3.968289955368382582e-01,1.038757357295467809e-01,8.262664932454300004e-02,2.319836596882640656e-01
4.438607100673760408e-01,9.048524074072902268e-01,1.895503551792622199e-01,5.303563903430958959e-01,9.059601697028534240e-01


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [15]:
f = open("credit_card.dat")
data = f.read()

binarydata=[]

lines = data.split()
shape1 = len(lines)-1
shape2 = len(lines[0])-4
for a in range(0,len(lines) - 1):
    characters = lines[a]
    for i in range(len(characters) - 4):
        binarydata.append(characters[i])
      

binarydata=np.array(binarydata).reshape(shape1,int(shape2/6),6)



In [16]:
def convert(asd):
    b = ""
    for asd2 in asd:
        a = ""
        for i in asd2:
            a = a + i 
        b = b + chr(int(a,2))
    return b

In [17]:
credit_card = np.array([convert(i) for i in binarydata])

In [18]:
print(credit_card)

['7648 5673 3775 2271' '3257 8247 3354 2266' '2722 0001 4011 6652'
 '0661 3063 3742 3150' '0432 1608 1462 4742' '5827 2027 8785 7303'
 '5774 8528 2087 1117' '8140 1210 6352 2845' '5764 1133 7301 7100'
 '6456 1737 4126 6726' '1228 8631 7382 0000' '7051 0160 5374 3166'
 '0618 3587 1630 6376' '1545 5454 7444 5636' '6735 3116 3202 6834'
 '7287 5011 1547 8413' '7033 2607 3328 4200' '2568 5244 1874 5024'
 '1684 2253 7570 7118' '0672 2576 0575 6631' '6332 8353 8787 1340'
 '1813 3361 1175 4211' '2477 6450 8840 2368' '5512 3505 2563 1326'
 '3083 7882 0621 0025' '4521 5148 8045 0334' '7563 3654 8713 5787'
 '8324 2664 0476 5561' '0565 2504 7168 3510' '5107 5507 1767 0738'
 '2462 1821 2448 1443' '2788 0638 6861 6554' '5851 5873 5474 0547'
 '0670 1004 4013 2655' '5874 5506 3048 0806' '2805 5401 8462 1260'
 '5083 8406 6310 1862' '1076 1445 3013 2266' '8440 4804 4844 5277'
 '4758 6141 0686 1387' '7586 0675 0315 2568' '2544 1258 7432 5165'
 '3474 5023 4434 5626' '1410 0270 0434 5086' '7315 4446 1104 4

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

In [21]:
!ls

00ex_introduction.ipynb         07.1ex_Algorithms.ipynb
01ex_Fundamentals.ipynb         README.md
02ex_NumberRepresentation.ipynb Untitled1.ipynb
03ex_Numpy.ipynb                cities.txt
04ex_OSEMN.ipynb                credit_card.dat
05ex_Pandas.ipynb               populations.txt
06ex_Visualization.ipynb


In [19]:
data = pd.read_json(r'user_data.json')

ValueError: Expected object or value

In [ ]:
filteredata=data.to_numpy()[data.to_numpy()[:,1] == 'American Express']

In [20]:
data = pd.DataFrame(data = filteredata,columns = data.columns.values)
data

NameError: name 'filteredata' is not defined

In [ ]:
data.to_csv('user_data.csv',index = False)
!cat user_data.csv
!rm user_data.csv

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


In [ ]:
df = pd.read_csv("https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1")

In [ ]:
df

In [ ]:
df['class'].hist()

7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

In [ ]:
df = pd.read_csv("https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1")

In [ ]:
df.plot.scatter('features_1','features_2')
df.plot.scatter('features_1','features_3')
df.plot.scatter('features_2','features_3')

8\. Load the same file of point 6, and convert the file to json with Pandas.

In [ ]:
df = pd.read_csv("https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1")
df.to_json(r'jasonfile.json')

In [ ]:
!cat jasonfile.json
!rm jasonfile.json