# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [19]:
a = np.random.rand(10)
print (a)
file1 = open(r"/Users/Sebastiano/data/simple_data.txt","w")
for i in range(0, len(a)):
    file1.write(str(a[i]) + '\n')
file1.close()

[0.7571641  0.11663676 0.21503456 0.29610796 0.01065232 0.06317556
 0.66400954 0.64065646 0.40390833 0.61629442]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [34]:
a = np.random.rand(7, 5)
print (a)
file2 = open(r"/Users/Sebastiano/data/data.txt","w")
for i in range(0, len(a)):
    for j in range(0, len(a[i])):
        if j != len(a[i]) -1:
            file2.write(str(a[i][j]) + " ")
        else:
            file2.write(str(a[i][j]))
    file2.write('\n')
file2.close()

[[0.75074191 0.02799188 0.92022128 0.9858595  0.23829853]
 [0.46818744 0.20420285 0.44619748 0.48526    0.91264136]
 [0.80057098 0.90681274 0.83152132 0.14421042 0.73430145]
 [0.80906314 0.89244468 0.59949447 0.28088285 0.76446575]
 [0.6715045  0.14960927 0.86306185 0.93336434 0.12275176]
 [0.87787392 0.49011799 0.69723074 0.39736432 0.30369193]
 [0.69815803 0.86225999 0.59790763 0.83098964 0.52083623]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [36]:
file_name = "/Users/Sebastiano/data/data.txt"
file3 = open(r"/Users/Sebastiano/data/data.csv","w")
with open(file_name, mode='r') as f:
    for line in f:
        #print (line)
        oldstr = line
        newstr = oldstr.replace(" ", ",")
        #for c in line.split(): 
            #print(c)
            #file3.write(c + ",")
        file3.write(newstr)
file3.close()

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.