1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [71]:
import numpy as np
import pandas as pd

x_1 = np.random.normal(0,1,size = [2000])
x_1 = x_1 - np.average(x_1)
x_2 = x_1 + np.random.normal(0,3,[2000])
x_2 = x_2 - np.average(x_2)
x_3 = 2*x_1+x_2
x_3 = x_3 - np.average(x_3)
df = np.vstack([x_1,x_2,x_3])
df = df.T

l_cov, V_cov = np.linalg.eig(np.cov(df.T))
U, spectrum, Vt = np.linalg.svd(df)

l_svd = spectrum**2/(len(df)-1)
V_svd = U

print(l_svd)
print()
print(l_cov)
print()

cumu_var = 0 # We start at 0 variability
mask = np.zeros(len(l_svd), dtype='bool')
for i, l in enumerate(l_svd):
    var = l/np.sum(l_svd)        
    print(f'Variability: {var*10000//1/100}')
    if cumu_var < 0.99:
        mask[i] = True
        cumu_var += var
new_df = V_svd.T@df
new_df[:,mask]

[2.49405099e+01 2.03924693e+00 1.33654461e-31]

[ 2.49405099e+01 -2.91468937e-16  2.03924693e+00]

Variability: 92.44
Variability: 7.55
Variability: 0.0


array([[-2.67642883e+01, -1.27681653e+02],
       [ 3.60589533e+01, -4.54320603e+01],
       [ 1.37806433e-14, -7.50510765e-14],
       ...,
       [-1.55431223e-15,  1.77635684e-15],
       [ 6.66133815e-16, -4.44089210e-16],
       [ 3.33066907e-16,  8.88178420e-16]])

2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 