1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [1]:
import numpy as np
import matplotlib as plt
from scipy import linalg as la
from matplotlib import pyplot 
import pandas as pd

##
mean = 0
std_1 = 1
std_2 = 3
N = 1000

x1 = np.random.normal(mean,std_1,N)
x2 = np.random.normal(mean,std_2,N)
x3 = 2*x1 + x2

m = pd.DataFrame({'x1':x1,'x2':x2,'x3':x3})
m

##

cov_m = np.cov(m,rowvar = False)
l,V = la.eig(cov_m)
print('Eigenvaues:',l)
print(V)

##
u,l_svd,vt = la.svd(m)
l_svd = l_svd**2/(N-1)
V_svd = vt
print("Eigenvalues : \n", l_svd)

Eigenvaues: [2.01764831e+01+0.j 2.01491916e-15+0.j 2.64357159e+00+0.j]
[[-0.08904902 -0.81649658  0.57044159]
 [-0.60959639 -0.40824829 -0.67950392]
 [-0.78769443  0.40824829  0.46137926]]
Eigenvalues : 
 [2.01764838e+01 2.64467175e+00 3.04297028e-31]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

In [15]:
N = 1000
x_1 = np.random.normal(0,1,N)
x_2 = x_1 + np.random.normal(0,3,N)

x_3 = 2*x_1 + x_2

y = np.array([np.random.normal(0,1/50,N) for i in range(10)])

x = np.array([x_1,x_2,x_3])
x = np.append(x,y)
print(np.shape(x))
print(np.shape(y))

####

cov_m = np.cov(x)
#l, V = la.eig(cov_m)
#lam = np.diag(1)
#lam = lam/lam.trace()

(13000,)
(10, 1000)


3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [30]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 

--2020-11-24 15:33:34--  https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1477391 (1.4M) [application/x-httpd-php]
Saving to: ‘/home/neo/data/magic04.data.1’

magic04.data.1      100%[===================>]   1.41M   333KB/s    in 4.3s    

2020-11-24 15:33:39 (333 KB/s) - ‘/home/neo/data/magic04.data.1’ saved [1477391/1477391]

--2020-11-24 15:33:40--  https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5400 (5.3K) [application/x-httpd-php]
Saving to: ‘/home/neo/data/magic04.names.1’

magic04.names.1     100%[=